export const USER_INFO = 'USER_INFO'
export const LOGOUT = 'LOGOUT'
export const AUTH = 'AUTH'
export const ERROR = 'ERROR'
export const BOOKMARK_POST = 'BOOKMARK_POST'
export const UPDATE_USER = 'UPDATE_USER'